name: classcheckup
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.7.1
  cupertino_icons: ^1.0.2
  curved_labeled_navigation_bar: ^2.0.2
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  firebase_storage: ^11.2.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  gauge_indicator: ^0.3.3
  google_sign_in: ^6.1.1
  image_picker: ^0.8.7+5
  shared_preferences: ^2.1.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21


flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Architect
      fonts:
        - asset: assets/fonts/Architect.ttf
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir-Medium.ttf
    - family: Fallscoming
      fonts:
        - asset: assets/fonts/Fallscoming.ttf
    - family: Itim
      fonts:
        - asset: assets/fonts/Itim-Regular.ttf
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
    - family: SourceSans
      fonts:
        - asset: assets/fonts/SourceSansPro-Regular.ttf
    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans-Regular.ttf
